name: Lint and test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: [self-hosted]
    env:
      CF_JOB_ID: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}_lint
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.CF_JOB_ID }}
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: recursive
          path: ${{ env.CF_JOB_ID }}

      - name: Install dependencies ☕️
        run: |
          source setup.sh ""

      - name: Lint 🔍
        run: |
          source setup.sh ""
          ./tests/run_linting

      - name: Cleanup 🧹
        if: always()
        run: |
          cd ..
          rm -rf "${CF_JOB_ID}"

  test:
    runs-on: [self-hosted]
    env:
      CF_JOB_ID: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}_test
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.CF_JOB_ID }}
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: recursive
          path: ${{ env.CF_JOB_ID }}

      - name: Install dependencies ☕️
        run: |
          source setup.sh ""

      - name: Test 🎢
        run: |
          source setup.sh ""
          ./tests/run_tests

      - name: Cleanup 🧹
        if: always()
        run: |
          cd ..
          rm -rf "${CF_JOB_ID}"

  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          pip install -U pip
          pip install twine

      - name: Check bundling 📦
        run: python setup.py sdist

      - name: Check setup 🚦
        run: twine check "dist/$( python setup.py --fullname ).tar.gz"

  coverage:
    needs: test
    runs-on: [self-hosted]
    env:
      CF_JOB_ID: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}_coverage
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.CF_JOB_ID }}
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: recursive
          path: ${{ env.CF_JOB_ID }}

      - name: Install dependencies ☕️
        run: |
          source setup.sh ""

      - name: Run coverage test 🎢
        run: |
          source setup.sh ""
          ./tests/run_coverage
          ls -al

      - name: Upload report 🔝
        uses: codecov/codecov-action@v2
        with:
          flags: unittests
          working-directory: ${{ env.CF_JOB_ID }}
          files: coverage_test_util.xml,coverage_test_columnar_util.xml
          verbose: true

      - name: Cleanup 🧹
        if: always()
        run: |
          cd ..
          rm -rf "${CF_JOB_ID}"
